name: After wf

on:
  workflow_run:
    workflows:
      - Main wf
    types:
      - completed

jobs:

  search-logs:

    runs-on: ubuntu-latest

    steps:

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      
      - name: Find and run ${{ env.SCRIPT }}
        run: |
          if [ -x "$SCRIPT" ]; then
            ${SCRIPT}
          fi
        env:
          SCRIPT: ./scripts/search-logs.sh
          RUN_ID: ${{ github.event.workflow_run.id }}
          GH_TOKEN: ${{ github.token }}
