name: Use ENV in runner

on:
  workflow_dispatch:
  push:
    paths:
      - 'aws/crossplane/*/**'
      - 'azure/crossplane/*/**'
      - 'gcp/crossplane/*/**'
      - 'multicloud/crossplane/*/**'

jobs:

  # one:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     packages: ${{ steps.list.outputs.packages }}

  #   steps:

    # - name: Clone Repo
    #   uses: actions/checkout@v3
    #   with:
    #     fetch-depth: '0'

    # - name: List changed files in PR
    #   id: list
    #   shell: bash
    #   run: |
    #     packages=$(git diff-tree --name-only -r --diff-filter=ACM HEAD~1 HEAD | grep -E '^[^/]+/crossplane/' | cut -d/ -f-3 | jq -ncrR '[inputs]|unique|map(split("/")|{"provider":.[0],"name":.[2]})|{"include":.}')
    #     echo "packages=$packages" >> $GITHUB_OUTPUT

  bump-version:
    uses: ./.github/workflows/bump-version.yml

  list-packages:
    uses: ./.github/workflows/list-packages.yml
    with:
      basedir: packages

  publish:
    needs:
      - bump-version
      - list-packages
    uses: ./.github/workflows/publish.yml
    strategy:
      matrix: ${{ fromJson(needs.list-packages.outputs.packages) }}
    with:
      package: ${{ matrix.name }}
      provider: ${{ matrix.provider }}
      version: ${{ needs.bump-version.outputs.version }}
      run-test: true
