name: Use ENV in runner

on:
  workflow_dispatch:
  push:
    paths:
      - 'packages/**'

jobs:

  list-packages:
    uses: ./.github/workflows/list-packages.yml
    with:
      basedir: packages

  filter-packages:
    runs-on: ubuntu-latest
    needs:
      - list-packages
    outputs:
      crossplane: ${{ steps.filter.outputs.crossplane }}
      carvel: ${{ steps.filter.outputs.carvel }}
    steps:
      - name: Filter packages
        id: filter
        run: |
          echo crossplane=$(jq -c '.include|=map(select(.operator=="crossplane"))' <<< $PACKAGES) >> $GITHUB_OUTPUT
          echo carvel=$(jq -c '.include|=map(select(.operator!="crossplane"))' <<< $PACKAGES) >> $GITHUB_OUTPUT
        env:
          PACKAGES: ${{ needs.list-packages.outputs.packages }}

  bump-version:
    uses: ./.github/workflows/bump-version.yml

  crossplane-publish:
    needs:
      - bump-version
      - filter-packages
    uses: ./.github/workflows/crossplane-publish.yml
    strategy:
      matrix: ${{ fromJson(needs.filter-packages.outputs.crossplane) }}
    with:
      package_name: ${{ matrix.name }}
      package_provider: ${{ matrix.provider }}
      package_version: ${{ needs.bump-version.outputs.version }}
      run-test: true

  carvel-publish:
    needs:
      - bump-version
      - filter-packages
    uses: ./.github/workflows/carvel-publish.yml
    strategy:
      matrix: ${{ fromJson(needs.filter-packages.outputs.carvel) }}
    with:
      package_name: ${{ matrix.name }}
      package_provider: ${{ matrix.provider }}
      package_version: ${{ needs.bump-version.outputs.version }}
      run-test: true
