name: Publish packages

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    paths:
      - 'packages/*/*/*/**'

jobs:

  list-packages:
    uses: ./.github/workflows/list-packages.yml
    with:
      basedir: packages

  bump-version:
    if: needs.list-packages.outputs.crossplane_publish == 'true' || needs.list-packages.outputs.carvel_publish == 'true'
    uses: ./.github/workflows/bump-version.yml
    needs:
      - list-packages

  crossplane-publish:
    if: needs.list-packages.outputs.crossplane_publish == 'true'
    needs:
      - bump-version
      - list-packages
    uses: ./.github/workflows/crossplane-publish.yml
    strategy:
      matrix: ${{ fromJson(needs.list-packages.outputs.crossplane) }}
    with:
      package_name: ${{ matrix.name }}
      package_provider: ${{ matrix.provider }}
      package_version: ${{ needs.bump-version.outputs.version }}
      run-test: false

  carvel-publish:
    if: needs.list-packages.outputs.carvel_publish == 'true'
    needs:
      - bump-version
      - list-packages
    uses: ./.github/workflows/carvel-publish.yml
    strategy:
      matrix: ${{ fromJson(needs.list-packages.outputs.carvel) }}
    with:
      package_name: ${{ matrix.name }}
      package_provider: ${{ matrix.provider }}
      package_version: ${{ needs.bump-version.outputs.version }}
      run-test: false
