name: Main wf

on:
  push:
    branches:
      - main
    paths-ignore:
    - .github

env:
  SECRET: ${{ secrets.FAKE_SECRET_YAML}}

jobs:

  unmasked:
    runs-on: ubuntu-latest
    steps:
      - name: Set individual env variables
        run: |
          for k in $(yq -o=json <<<"$SECRET" | jq -r 'keys[]'); do
            K=$(echo $k | sed -r 's/([a-z0-9])([A-Z])/\1_\L\2/g' | tr '[:lower:]' '[:upper:]')
            echo $K=$(yq -o=json <<<"$SECRET" | jq -r '."'$k'"') >> $GITHUB_ENV
          done
      - name: Print secret
        run: |
          echo "$SECRET"
      - name: Print key
        run: |
          yq '."a-key"' <<<"$SECRET"
      - name: Print key
        run: |
          yq '."another-key"' <<<"$SECRET"
      - name: Print b64 key
        run: |
          yq '."a-key"' <<<"$SECRET" | base64
      - name: Print b64 key
        run: |
          yq '."another-key"' <<<"$SECRET" | base64

  masked:
    runs-on: ubuntu-latest
    steps:

      - name: Mask secret
        uses: matteo-magni/secret-mask-action@develop
        with:
          secret: ${{ env.SECRET }}

      - name: Set individual env variables
        run: |
          for k in $(yq -o=json <<<"$SECRET" | jq -r 'keys[]'); do
            K=$(echo $k | sed -r 's/([a-z0-9])([A-Z])/\1_\L\2/g' | tr '[:lower:]' '[:upper:]')
            echo $K=$(yq -o=json <<<"$SECRET" | jq -r '."'$k'"') >> $GITHUB_ENV
          done
      - name: Print secret
        run: |
          echo "$SECRET"
      - name: Print key
        run: |
          yq '."a-key"' <<<"$SECRET"
      - name: Print key
        run: |
          yq '."another-key"' <<<"$SECRET"
      - name: Print b64 key
        run: |
          yq '."a-key"' <<<"$SECRET" | base64
      - name: Print b64 key
        run: |
          yq '."another-key"' <<<"$SECRET" | base64
