name: Publish packages

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PACKAGES_BASEDIR: packages

on:

  push:
    branches:
      - main
    paths:
      - 'packages/*/*/*/**'

  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]
    branches:
      - main
    paths:
      - 'packages/*/*/*/**'

jobs:

  parameters:
    runs-on: ubuntu-latest

    outputs:
      packages_basedir: ${{ steps.params.outputs.packages_basedir}}

    steps:

      - name: Set parameters
        id: params
        run: |
          echo "packages_basedir=${PACKAGES_BASEDIR}" >> $GITHUB_OUTPUT

  list-packages:
    needs:
      - parameters
    uses: ./.github/workflows/list-packages.yml
    with:
      basedir: ${{ needs.parameters.outputs.packages_basedir }}

  bump-version:
    if: needs.list-packages.outputs.crossplane_publish == 'true' || needs.list-packages.outputs.carvel_publish == 'true'
    uses: ./.github/workflows/bump-version.yml
    needs:
      - list-packages

  crossplane-publish:
    if: needs.list-packages.outputs.crossplane_publish == 'true'
    needs:
      - bump-version
      - list-packages
    uses: ./.github/workflows/crossplane-publish.yml
    strategy:
      matrix: ${{ fromJson(needs.list-packages.outputs.crossplane) }}
    with:
      package_name: ${{ matrix.name }}
      package_provider: ${{ matrix.provider }}
      package_version: ${{ needs.bump-version.outputs.version }}
      run-test: ${{ github.event_name == 'pull_request' }}

  carvel-publish:
    if: needs.list-packages.outputs.carvel_publish == 'true'
    needs:
      - bump-version
      - list-packages
    uses: ./.github/workflows/carvel-publish.yml
    strategy:
      matrix: ${{ fromJson(needs.list-packages.outputs.carvel) }}
    with:
      package_name: ${{ matrix.name }}
      package_provider: ${{ matrix.provider }}
      package_version: ${{ needs.bump-version.outputs.version }}
      run-test: ${{ github.event_name == 'pull_request' }}
