name: Reusable publish workflow


on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
      package:
        type: string
        required: true
      provider:
        type: string
        required: true
      run-test:
        type: boolean
        default: false
      kubernetes-version:
        type: string
        default: v1.24.6
      kind-version:
        type: string
        default: v0.16.0
    outputs:
      package_repository:
        value: ${{ jobs.publish.outputs.package_repository }}
      package_registry:
        value: ${{ jobs.publish.outputs.package_registry }}

jobs:

  publish:
    runs-on: ubuntu-latest

    outputs:
      package_repository: ${{ env.PACKAGE_REPOSITORY }}
      package_registry: ${{ env.PACKAGE_REGISTRY }}

    env:
      PACKAGE_VERSION: ${{ inputs.version }}
      PACKAGE_REGISTRY: ghcr.io
      PACKAGE_REPOSITORY: ${{ github.repository }}/${{ inputs.provider }}/crossplane/${{ inputs.package }}
      PACKAGE_PROVIDER: ${{ inputs.provider }}
      PACKAGE_NAME: ${{ inputs.package }}

    steps:

      - name: Dump info
        run: |
          env | sort

  test:
    runs-on: ubuntu-latest
    needs:
      - publish
    if: inputs.run-test
    env:
      CONFIG_VERSION: ${{ inputs.version }}
      CONFIG_IMAGE: ${{ needs.publish.outputs.package_registry }}/${{ needs.publish.outputs.package_repository }}

    steps:

      - name: Dump info
        run: |
          env | sort

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0
        with:
          verbosity: 5
          version: ${{ inputs.kind-version }}
          kubectl_version: ${{ inputs.kubernetes-version }}
          node_image: kindest/node:${{ inputs.kubernetes-version }}

      - name: Verify Cluster
        run: |
          kubectl version
          which kubectl
          kubectl cluster-info
          kubectl get storageclass standard

      - name: Test Crossplane MongoDB Package
        if: inputs.package == 'mongodb'
        run: |
          echo ./crossplane-e2e-mongodb.sh
          exit 1

      - name: Cleanup MongoDB Package
        if: always() && inputs.package == 'mongodb'
        run: |
          echo ./mongodb/crossplane-e2e-cleanup.sh
