name: Reusable publish workflow


on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
      package:
        type: string
        required: true
      provider:
        type: string
        required: true
      run-test:
        type: boolean
        default: false
    outputs:
      package_repository:
        value: ${{ jobs.publish.outputs.package_repository }}
      package_registry:
        value: ${{ jobs.publish.outputs.package_registry }}

jobs:

  publish:
    runs-on: ubuntu-latest

    outputs:
      package_repository: ${{ env.PACKAGE_REPOSITORY }}
      package_registry: ${{ env.PACKAGE_REGISTRY }}

    env:
      PACKAGE_VERSION: ${{ inputs.version }}
      PACKAGE_REGISTRY: ghcr.io
      PACKAGE_REPOSITORY: ${{ github.repository }}/${{ inputs.provider }}/crossplane/${{ inputs.package }}
      PACKAGE_PROVIDER: ${{ inputs.provider }}
      PACKAGE_NAME: ${{ inputs.package }}

    steps:

      - name: Dump info
        run: |
          env | sort

  test:
    runs-on: ubuntu-latest
    needs:
      - publish
    if: inputs.run-test
    env:
      CONFIG_VERSION: ${{ inputs.version }}
      CONFIG_IMAGE: ${{ needs.publish.outputs.package_registry }}/${{ needs.publish.outputs.package_repository }}

    steps:

      - name: Dump info
        run: |
          env | sort
