name: Reusable test workflow


on:
  workflow_call:
    inputs:
      package_version:
        type: string
        required: true
      package_name:
        type: string
        required: true
      package_provider:
        type: string
        required: true
      kubernetes-version:
        type: string
        default: v1.24.6
      kind-version:
        type: string
        default: v0.16.0

jobs:

  test:
    runs-on: ubuntu-latest
    env:
      CONFIG_VERSION: ${{ inputs.package_version }}
      CONFIG_IMAGE: ${{ inputs.package_registry }}/${{ inputs.package_repository }}

    steps:

      - name: Dump info
        run: |
          env | sort

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0
        with:
          verbosity: 5
          version: ${{ inputs.kind-version }}
          kubectl_version: ${{ inputs.kubernetes-version }}
          node_image: kindest/node:${{ inputs.kubernetes-version }}

      - name: Verify Cluster
        run: |
          kubectl version
          which kubectl
          kubectl cluster-info
          kubectl get storageclass standard

      - name: Create Azure Config Secret
        if: inputs.provider == 'azure'
        run: |
          kubectl create namespace upbound-system
          kubectl create secret generic azure-secret -n upbound-system --from-literal=creds='${{ secrets.AZURE_CONFIG }}'

      - name: Test Crossplane Package
        run: |
          [ -x ${{ env.SCRIPT }} ] && ${{ env.SCRIPT }} || true
        env:
          SCRIPT: ./scripts/crossplane-e2e-${{ inputs.package_name }}.sh

      - name: Cleanup Package
        run: |
          [ -x ${{ env.SCRIPT }} ] && ${{ env.SCRIPT }} || true
        env:
          SCRIPT: ./scripts/crossplane-e2e-${{ inputs.package_name }}/cleanup.sh
